version: 2
jobs:
  build:
    working_directory: ~/blockchain-explorer-sdk
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/blockchain-explorer-sdk/.npmrc
      - run:
            name: set Registry
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build the 'dist' folder
          command: npm run build-production
      - run: ls -al
      - persist_to_workspace:
          root: dist
          paths:
            - index.js

  test:
    working_directory: ~/blockchain-explorer-sdk
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/blockchain-explorer-sdk/.npmrc
      - run:
            name: set Registry
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - run:
          name: unit-test
          command:  npm run test:coverage
      - run:
          name: plato
          command:  npm run plato
      - store_artifacts:
          path: ./reports/
          destination: reports
  publish:
    working_directory: ~/blockchain-explorer-sdk
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - attach_workspace:
          at: ~/blockchain-explorer-sdk/dist
      - run: ls -al
      - run:
          name: Append circleCI build number to version
          command: |
            git config user.email "devops@pillar.io"
            git config user.name "Issabot"
            npm version $(node -e "const currentVersion=require('./package.json').version; const firstTwoDots=currentVersion.substring(0, currentVersion.lastIndexOf('.')+1); console.log(firstTwoDots);")$CIRCLE_BUILD_NUM
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/blockchain-explorer-sdk/.npmrc
      - run:
          name: Publish Package to Artifactory
          command: npm publish   --registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
