version: 2
jobs:
  build:
    working_directory: ~/blockchain-explorer-sdk
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/blockchain-explorer-sdk/.npmrc
      - run:
            name: set Registry
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - run:
          name: Install TypeScript packages globally
          command: sudo yarn global add typescript tsc ts-node
      - run:
          name: Compile TypeScript to JS
          command: tsc
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test:
    working_directory: ~/blockchain-explorer-sdk
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/blockchain-explorer-sdk/.npmrc
      - run:
            name: set Registry
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - run:
          name: unit-test
          command:  npm run test:coverage
      - run:
          name: plato
          command:  npm run plato
      - store_artifacts:
          path: ./reports/
          destination: reports
  publish:
    working_directory: ~/blockchain-explorer-sdk
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Append circleCI build number to version
          command: |
            git config user.email "devops@pillar.io"
            git config user.name "Issabot"
            npm version $(node -e "console.log( require('./package.json').version )")-$CIRCLE_BUILD_NUM
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/blockchain-explorer-sdk/.npmrc
      - run:
          name: Publish Package to Artifactory
          command: npm publish   --registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
