version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    working_directory: ~/blockchain-explorer-sdk
    docker:
      - image: circleci/node:10.14.0
    steps:
      - checkout
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/blockchain-explorer-sdk/.npmrc
      - run:
            name: set Registry
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build the 'dist' folder
          command: npm run build-production
      - run: ls -al
      - persist_to_workspace:
          root: dist
          paths:
            - index.js
      - slack/status:
          fail_only: true
          failure_message: "Triggered by: *${CIRCLE_USERNAME}* \n\n Oops! Since *$CIRCLE_JOB* has failed no tests can be run! :circleci-fail:"
          webhook: "${SLACK_WEBHOOK_URL}"

  tests:
    working_directory: ~/blockchain-explorer-sdk
    docker:
      - image: circleci/node:10.14.0
    steps:
      - checkout
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/blockchain-explorer-sdk/.npmrc
      - run:
            name: set Registry
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - run:
          name: unit-test
          command:  npm run test:coverage
      - run:
          name: plato
          command:  npm run plato
      - store_artifacts:
          path: ./reports/
          destination: reports
      - slack/status:
          fail_only: true
          failure_message: "Triggered by: *${CIRCLE_USERNAME}* \n\n Oops! *$CIRCLE_JOB* have failed, please fix them! :circleci-fail:"
          webhook: "${SLACK_WEBHOOK_URL}"

  publish:
    working_directory: ~/blockchain-explorer-sdk
    docker:
      - image: circleci/node:10.14.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/blockchain-explorer-sdk/dist
      - run: ls -al
      - run:
          name: Append circleCI build number to version
          command: |
            git config user.email "devops@pillar.io"
            git config user.name "Issabot"
            npm version $(node -e "const currentVersion=require('./package.json').version; const firstTwoDots=currentVersion.substring(0, currentVersion.lastIndexOf('.')+1); console.log(firstTwoDots);")$CIRCLE_BUILD_NUM
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/blockchain-explorer-sdk/.npmrc
      - run:
          name: Publish Package to Artifactory
          command: npm publish   --registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - run:
          name: Announce Publish
          command: |
            chmod +x .circleci/announcePublish.sh
            .circleci/announcePublish.sh "BCX SDK" "$(node -e "console.log(require('./package.json').name)")@$(node -e "console.log(require('./package.json').version)")"
      - slack/status:
          fail_only: true
          failure_message: "Triggered by: *${CIRCLE_USERNAME}* \n\n Failed, new package is not published! :circleci-fail:"
          webhook: "${SLACK_WEBHOOK_URL}"

workflows:
  version: 2.1
  build_test_and_deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
      - publish:
          requires:
            - tests
          filters:
            branches:
              only:
                  - master
